[server]
port = 5555
bind-host = true

[node]
# Адрес хаба
driver = ["chrome"]
hub = "http://localhost:4444"

# Сколько браузеров может быть открыто одновременно
max-sessions = 2
detect-drivers = false

session-timeout = 120
heartbeat-period = 30

[[node.driver-configuration]]
display-name = "SpookyChrome"
max-sessions = 2
stereotype = {"browserName" = "chrome"}